# fly.toml app configuration file generated for timeleftjs on 2024-04-10T20:52:25-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'timeleftjs'
primary_region = 'bos'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
